# For more information: https://laravel.com/docs/sail
version: "3"
services:
    nova.cms:
        build:
            context: ./local-docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: nova-8.1/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT}:80"
            - 8888:8000
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
            # - 'nova-mysql:/var/www/html/storage/app/public'
        networks:
            - nova
        depends_on:
            - nova.mysql
    #            - nova.redis
    nova.mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3310}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 2
        volumes:
            - "nova-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - nova
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3

            timeout: 5s
    nova.mailhog:
        image: "mailhog/mailhog:latest"
        ports:
            - 1026:1025
            - 8026:8025
        networks:
            - nova
    nova.phpmyadmin:
        image: "phpmyadmin:latest"
        ports:
            - 8082:80
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: 500M
        links:
            - "nova.mysql:db"
        depends_on:
            - nova.mysql
        networks:
            - nova
networks:
    nova:
        driver: bridge
volumes:
    nova-storage:
        driver: local
    nova-mysql:
        driver: local
